### ISSUE TITLE
very long startup time on i9 with intel ARC iris Xe Graphics

### ISSUE THREAD

**Issue by energiebrand** [Steffenhir/GraXpert#115]
I changed from an old i5 7600 PC ( NVIDEA 1050ti) to an i9 mini-PC with intel ARC iris Xe Graphics (embedded graphics card).

When starting GraXpert 2.0.2 it takes about 55sec after showing the GraXpert pop-up windows until the GUI is shown and the program can be used. I don't know the reason but is there anything in the code which tries to evaluate something (hardware configuration)? If yes would it be possible in a future release if some configuration can be stored permanently in a config-file to avoid this?

When starting the Beta 2.1.1 release the first start up is faster. And if started once, closed and started again it comes up in some seconds. So there seems to be changed something and some information seems to be cashed I think. However the first start up does take longer but not 55sec as with the 2.0.2 release.

**Comment by schmelly** [comment]
Hi @energiebrand,

thanks for raising this issue. It is known to us and adressed in GraXpert >= 2.1.0. The reason for the slow startup since 2.0.x is in the additional, large tensorflow dependency for GraXpert AI and how we package GraXpert: the GraXpert .exe is basically a self-extracting archive. I.e., during each startup, the application is unpacked to some temporary folder and executed from there. Typically, some antimalware tool, e.g., MS Smartscreen, will kick in also which will slows startup even further. This has been adressed since 2.1.0 by packaging GraXpert as an .msi installer package.

In a future release we plan to reduce GraXperts memory footprint again by switching from tensorflow to another AI runtime.

Best regards and CS
David
