### ISSUE TITLE
New GraxPert install on fresh pc

### ISSUE THREAD

**Issue by TFX18** [Steffenhir/GraXpert#136]
Hi guys, I've just installed PI and all plugins on a new laptop and I have now some problems with GraXpert :(
If I launch the standalone version i couldn't select the AI model in the advanced tab 👍 
![immagine_2024-04-23_193927239](https://github.com/Steffenhir/GraXpert/assets/46243272/573d4f6a-b15d-4867-a88a-5c54e9fcf7ca)

On the other hand, If I try to use the PI plugin, i get this error message:
![immagine_2024-04-23_194114700](https://github.com/Steffenhir/GraXpert/assets/46243272/be7b3ebc-9b9f-43c8-a318-284aa1670b54)

![immagine_2024-04-23_202111784](https://github.com/Steffenhir/GraXpert/assets/46243272/df7f0011-d962-449f-b86d-b40b7dd2a7b9)

This is a new W11 laptop and I have already installed both Visual C++ x86 and x64.

Any other suggestions? :(

**Comment by schmelly** [comment]
Hi,

GraXpert connects to our s3 storage during startup in order to query the available models. Please ensure the computer where you want to use GraXpert has an internet connection to be able to download the appropriate models once.

If it has please try to enter the address www.schmelly.de in a browser and see if that works. If yes I suspect some anti malware engine is blocking outgoing connections from Graxpert.

Best regards
David

**Comment by TFX18** [comment]
Thanks a lot for this tip...i din't realized that with the new win install the clock wasn't synchronized with local time. Fixing this has solved all the problems! Thanks a lot for help
